### ISSUE TITLE
I don't see UNC as target of deployment

### ISSUE THREAD

**Issue by artisticcheese** [mkloubert/vs-deploy#1]
Is it possible to utilize just SMB share as destination?

**Comment by mkloubert** [comment]
Yes it is implemented! :-)

The target type is `local` as for a "real" local folders (the term `local folder` might be a little bit misleading here).

You can use any path format that [Node.js](https://nodejs.org/en/) supports on your machine.

Example for SMB based network path:

```json
{
    "deploy": {
        "targets": [
            {
                "type": "local",
                "name": "My network folder",
                "description": "A SMB shared network folder",
                "dir": "\\\\MyServer\\my_package_files"
            }
        ]
    }
}
```

**Comment by artisticcheese** [comment]
You are awesome
