### ISSUE TITLE
Deploy Settings Need 2 Targets

### ISSUE THREAD

**Issue by rivenvirus** [mkloubert/vs-deploy#10]
Hello, I have found that if I only set one target deploy does not work, when adding a second target the deploy works

Example:

`{
    "deploy": {
        "targets": [
            {
                "type": "sftp",
                "name": "My Deploy",
                "description": "A SFTP folder",
                "dir": "/folder",
                "host": "host.com", "port": 22,
                "user": "user", "privateKey": "/.ssh/id_rsa"
            },{
                "type": "test",
                "name": "Second target to work",
                "description": "A test target"
            }
        ]
    }
}`

Regards!!

**Comment by mkloubert** [comment]
What does the output (`CTRL + SHIFT + U`, selecting `Deploy`) say?
