### ISSUE TITLE
vscode warning - Incorrect type. Expected "object"

### ISSUE THREAD

**Issue by binary64** [mkloubert/vs-deploy#102]
I have

```json
"host": [
            {
                "dir": "./files_from_remotes"
            }
        ]
```
Taken from the first page of your wiki. But my vscode is saying `Incorrect type. Expected "object"`

What is wrong here?

**Comment by mkloubert** [comment]
@binary64 

You used an array instead of an object.

The right way shows the following example:

```json
{
    "deploy": {
        "host": {
            "dir": "./files_from_remotes"
        }
    }
}
```
