### ISSUE TITLE
Feature Request: Disable Notifications

### ISSUE THREAD

**Issue by strongui** [mkloubert/vs-deploy#103]
I love the plugin, but it's really annoying having to **escape** the notification _"...has been deploywed to..."_

Maybe add it as a setting or something? I already have the info in the console drawer, I don't need a popup every time. 

Thanks!

**Comment by mkloubert** [comment]
@strongui 

You can setup [showPopupOnSuccess](https://github.com/mkloubert/vs-deploy/issues/68#issuecomment-301120445) setting to disable these kind of popups.
