### ISSUE TITLE
Multi-root support for upcoming VSCode release

### ISSUE THREAD

**Issue by WraithKenny** [mkloubert/vs-deploy#112]
VS Code will have support for multiple root folders in the next release, and vs-deploy will have to be updated to support it. Currently on the "Insiders" release, if you configure a multi-root project, and edit your Workspace Settings to contain only one folder, vs-deploy still works fine, but if you have more than 1 folder in the Workspace, things stop working as expected.

https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs

**Comment by mkloubert** [comment]
@WraithKenny 

Thank you very much for the feedback!

I will spend my time with refactoring to the new API, otherwise we have a non working extension here, when the upcoming release arrives!

**Comment by WraithKenny** [comment]
Hello again! I've been thinking on this issue, and I've seen the commit were you refactored `workspace.getRootPath()`, which is great.

I'm thinking that the difference between `window` and `resource` is important to vs-deploy.
https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#settings

Currently, your settings are on the default (`window`) but might make more sense as `resource`. This means that the `.vscode/settings.json` file were we used to put our deploy config would still be used but on a rootFolder by rootFolder basis, which I think makes sense.

If the settings are `window` based, then users who move to multi-root project have to migrate to the `xxx.code-workspace` file, and more importantly its unclear to what folder(s) those settings would apply to (and would seem to need a much bigger code refactor to fully support).

**Comment by mkloubert** [comment]
Should be have a much better support in [new extension](https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-deploy-reloaded).

That you very very much for your help! @WraithKenny
