### ISSUE TITLE
command 'extension.deploy.file' not found

### ISSUE THREAD

**Issue by emmafull** [mkloubert/vs-deploy#115]
The warn message "command 'extension.deploy' not found" is shown when trying to deploy to a sftp target. Nothing is shown in the debug console. I've tried reinstalling the extension, reinstalling VSCode, and resetting my config. VSCode 1.17.1, Deploy 10.0.0, macOS High Sierra 10.13. Here is part of my config:
```       
        "deploy": {
            "targets": [
                {
                    "type": "sftp",
                    "name": "foo",
                    "description": "foobar",
                    "dir": "/",
                    "host": "foobarbaz", 
                    "port": 22,
                    "user": "xxxx", 
                    "password": "xxxx"
                }
            ]
        }
```

**Comment by mkloubert** [comment]
@emmafull 

Have you tried to uninstall and reinstall the extension?

**Comment by emmafull** [comment]
@mkloubert Yes. I've also uninstalled and reinstalled VSCode.

**Comment by miriejob** [comment]
I have the same situation.
VSCode 1.17.1 + vs-deploy 9.34.1 is ok, but VSCode 1.17.1 + vs-deploy 10.0.0 shows "command 'extension.deploy' not found".

**Comment by mkloubert** [comment]
@emmafull @miriejob 

Unfortunately I cannot reproduce the bug.

Do you have a `.vscode` folder inside your workspace or did you define your deploy settings globally?

The last change I did was, that I changed the [activationEvents](https://code.visualstudio.com/docs/extensionAPI/activation-events) from `*` to `"workspaceContains:/.vscode"`, what means that the extension is only activated when a `.vscode` folder exists.

Does the debug console (`CTRL + SHIFT + Y`) tells someting?

**Comment by emmafull** [comment]
@mkloubert - Unfortunately nothing is in the debug console.
Here are my locations of `.vscode`:
```
./.vscode
./.vscode/extensions/mkloubert.vs-deploy-10.0.0/node_modules/jsftp/.vscode
```

**Comment by miriejob** [comment]
@mkloubert
Oh, I used global settings in previous version...
After copying {workspace}/.vscode/settings.json (and reboot vscode), it works!
Thank you for your assistance.

**Comment by mkloubert** [comment]
@miriejob 
Ah, OK.

Can you tell me kind the "features" you setuped in your "global" config? Where these things, that can only be used for a special project or did you define things that should also be shared with other projects?

@emmafull 
Is that `./.vscode/extensions/mkloubert.vs-deploy-10.0.0/*` stored inside your workspace?

**Comment by emmafull** [comment]
My apologies, at the time of my last post it was not in my workspace. However, now it is and I’m able to deploy again! Thank you very much @mkloubert

**Comment by miriejob** [comment]
I didn't consider well.. My setting about vs-deploy is
```
    "deploy": {
        "openOutputOnDeploy": false,
        "showPopupOnSuccess": false,
        "showDeployResultInStatusBar": true,
        "packages": [
            {
                "name": "Version 2.3.4",
                "description": "Package version 2.3.4",
                "files": [foo],
                "deployOnSave": false
            }
        ],
        "targets": [
            {
                "name": "",
                "type": "sftp",
                "dir": "",
                "host": "",
                "port": ,
                "user": "",
                "privateKey": ""
            }
        ]
    },
```

In my case, It's not necessary defining the deploy settings in global.

**Comment by andremacola** [comment]
I'm having this problem too

**Comment by redapplewithleaves** [comment]
I am also having the same issue:
![image](https://user-images.githubusercontent.com/9419314/31900626-ec5a2aba-b7d3-11e7-94a3-0a47c9b10131.png)

This is in my {workspace}/.vscode/settings.json:
{
    "deploy": {
        "packages": [
            {
                "name": "UI Version 2.0.4",
                "description": "UI Version 2.0.4",
                "include":[
                    "app/**"
                ],
                "exclude": [
                    ".git/**",
                    ".vscode/**",
                    "bower_components/**"
                ],
                "deployOnSave": false
            },
            {
                "name": "Version 2.3.5 (anything)",
                "description": "Package version 2.3.5"
            }
        ],
        "targets": [
            {
                "type": "zip",
                "name": "My ZIP file",
                "description": "Create a ZIP file in a target directory",

                "open": false,
                "target": "E:/test"
            }
        ]
    }
}

**Comment by mkloubert** [comment]
@redapplewithleaves 

What version of VSCode do you use?

**Comment by redapplewithleaves** [comment]
Ah, never mind. Re-installed the extension and it works again.
