### ISSUE TITLE
[SFTP]Support for key pair login

### ISSUE THREAD

**Issue by lcw0622** [mkloubert/vs-deploy#116]
It's a wonderful tool, thanks for everyone work for this.
I have read the wiki and didn't find description of key pair login for sftp. 
Is it possible to add 'ssh key pair login' feature in new version?
Thanks.

**Comment by mkloubert** [comment]
@lcw0622 

Sorry for the late answer: I think, that [this issue](https://github.com/mkloubert/vs-deploy/issues/108) should be similar to yours.

**Comment by lcw0622** [comment]
^_^Thanks a lot ,I advise to add _privateKey_ setting description to wiki.
