### ISSUE TITLE
v10.0.0 is completely unusable for me - stuck on Preparing deployment... forever

### ISSUE THREAD

**Issue by binary64** [mkloubert/vs-deploy#119]
It has made me realize that I perhaps can't ever use vscode again, because the plugin authors can push new code to my IDE at any time, it can break things when I least want them to break. The deployment is extremely important to remain stable.

Please can you rollback or fix this asap

We appreciate the plugin, your work, but at the same time we do rely on it heavily.

**Comment by mkloubert** [comment]
@binary64

Have you tried to install the extension [manually](https://stackoverflow.com/questions/37071388/how-to-install-vscode-extensions-offline) by using an older [VSIX release](https://github.com/mkloubert/vs-deploy/releases)?

I am very sorry for that ... I try to reproduce as many issues as I can, but in most cases it is a lack of time I have, and the reason why I released a new major version (v10) is, that Microsoft has decided to change important parts of the API like [this](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs).
