### ISSUE TITLE
Info Popup does not auto-close

### ISSUE THREAD

**Issue by jwang-navarik** [mkloubert/vs-deploy#123]
![image](https://user-images.githubusercontent.com/29586131/32743080-47e418e0-c860-11e7-82ff-eb5e96f478b4.png)

The above popup displays whenever deployment is triggered. What's annoying is it covers part of the editor area and it doesn't hide itself unless I manually click the close button. I wonder if there is a way to auto-hide the popup. If not possible, it would be OK if I can disable the popup in some settings.

**Comment by mkloubert** [comment]
@jwang-navarik 

VSCode wants that you have to close popups manually. It does not support auto close.

If you do not want to show a popup after each deployment, you can set [showPopupOnSuccess](https://github.com/mkloubert/vs-deploy/issues/68#issuecomment-301120445) setting.
