### ISSUE TITLE
TOC links in wiki not working

### ISSUE THREAD

**Issue by DavidA2014** [mkloubert/vs-deploy#129]
The links in the table of contents at https://marketplace.visualstudio.com/items?itemName=mkloubert.vs-deploy appear not to work.

**Comment by mkloubert** [comment]
Unfortunately Marketplace Markdown is not compatible with the GitHub one.

The best way is to switch to GitHub directly.

**Comment by DavidA2014** [comment]
Ok, thanks for replying.
