### ISSUE TITLE
[Help wanted] How to FTP C++ executable?

### ISSUE THREAD

**Issue by DavidA2014** [mkloubert/vs-deploy#130]
I have Build Task that builds a C++ executable. I want to copy that executable to a remote target using FTP.  How would I do that using Deploy?

**Comment by mkloubert** [comment]
You can use "deploy on change" feature which can deploy things that are change, like generated executables.

**Comment by DavidA2014** [comment]
Thanks for your answer.

**Comment by DavidA2014** [comment]
I want to deploy file ../srcpath/outfile to /dstpath/outpath, where srcpath  and destpath are different.  So I tried:
    "deploy": {
        "button": {
          "enabled": true,
          "test": "Deploy myApp",
          "packages": [ "myApp" ]
        },

        "packages": [
            {
                "name": "myApp",
                "description": "Package version 2.3.4",
                "files": [
                    "myApp.out"
                ],
                "loadFrom": "../srcpath/",
                ],
                "deployOnSave": true,
                "targets": [
                  "myApp"
                ]
            }
        ],

        "targets": [
            {
                "type": "sftp",
                "name": "myApp",
                "description": "my target",
                "dir": "destpath",
                <snip>
            }
        ]
    }

Is that strategy (using loadFrom) the correct way to go?

I get error:

"Loading data from 'c:\SVNProj\myPath\' failed: Error: EISDIR: illegal operation on a directory, read"

but the path shown in the error message is valid

**Comment by mkloubert** [comment]
Because you use a build task, you should use [deploy on change](https://github.com/mkloubert/vs-deploy/wiki/deploy_on_change) instead.

The difference is that "deploy on save" is fired when you explicitly save the file in your editor, and "deploy on change" means that anything, like you or a background build task, changes a file.

Btw.: The use of `loadFrom` is wrong where. It means that you define a path to a file, which settings should be merged with the package.

```json
{
    "deploy": {
        "packages": [
            {
                "name": "My project",
                
                "deployOnChange": {
                    "files": [ "myApp.out" ],
                    "useTargetList": true
                },

                "targets": [ "myApp" ]
            }
        ],

        "targets": [        
            {
                "name": "myApp",
                "type": "sftp"
            }
        ]
    }
}
```

**Comment by DavidA2014** [comment]
Thanks for your reply. So I now have:

    "deploy": {

        "packages": [
            {
                "name": "My project",

                "deployOnChange": {
                    "files": [
                        "Source/LedaAP_workbench/LedaAP/NonDebug/LedaAP.out"
                    ],
                    "useTargetList": true
                },

                "targets": [ "ledapc" ]
            }
        ],

        "targets": [
            {
                "type": "sftp",
                "name": "ledapc",
                "dir": "/home/mydir"
                <snip>
            }
        ]
    }

but nothing is appearing /home/mydir on the target after the project gets built.  Can you see anything wrong?

Please note that I would like the destination to be:

/home/mydir/LedaAP.out

not

/home/mydir/Source/LedaAP_workbench/LedaAP/NonDebug/LedaAP.out

**Comment by DavidA2014** [comment]
Sorry, the file I specified is being deployed successfully. However, my second question is still valid, that is:

I want the destination to be:
    /home/mydir/LedaAP.out
not
    /home/mydir/Source/LedaAP_workbench/LedaAP/NonDebug/LedaAP.out

Is it possible to configure that in Deploy's settings?

**Comment by mkloubert** [comment]
Yes, you can use [folder mappings](https://github.com/mkloubert/vs-deploy/wiki/folder_mappings).

**Comment by DavidA2014** [comment]
Thanks, folder mappings does what I need.

I am deploying one file:

        "packages": [
            {
                "name": "My project",

                "deployOnChange": {
                    "files": [
                        "Source/<snip>/LedaAP.out"
                    ],
                    "useTargetList": true
                },

                "targets": [ "ledapc" ]
            }
        ],

but get two deploy messages:

    Deploying file 'c:/SVNProj/<snip>/LedaAP.out' to '/home/me' ('ledapc')... 
    Deploying file 'c:/SVNProj/<snip>/LedaAP.out' to '/home/me' ('ledapc')...  [OK]
    Finished
    [OK]
    Finished

Is that expected?

**Comment by mkloubert** [comment]
The build task is creating the `LedaAP.out` in background and you do not save this file in your editor, right?

Maybe the build task changes / creates the file twice, what means that "file change event" is also fired twice.

**Comment by DavidA2014** [comment]
Yes, it's built in the background. Thanks for your explanation.
