### ISSUE TITLE
[Help Wanted] disable popup and output window from popping up

### ISSUE THREAD

**Issue by kingmomo** [mkloubert/vs-deploy#131]
help....

Is there a way we can disable the popup window that shows up on saving files?

Also, everytime on save or deploy, output window shows up. Can that be disabled as well?

Thanks for this extension!!

**Comment by mkloubert** [comment]
There are the settings showPopupOnSuccess and openOutputOnDeploy, which can be set to (false).

**Comment by kingmomo** [comment]
Thanks @mkloubert for getting back. I see its defined in wiki (my bad).

But where do I give these options? I tried in both the "packages" and "targets" and it doesnt seem to work. Restarted vscode after making the change as well.

**Comment by mkloubert** [comment]
You have to do it globally, inside "deloy" section and outside "packages" and "targets" sections.

**Comment by kingmomo** [comment]
Works like a charm 👍 
Thanks for the quick response.
