### ISSUE TITLE
Support private key file for SSH authentication?

### ISSUE THREAD

**Issue by DavidA2014** [mkloubert/vs-deploy#132]
When using SFTP, I would like to be able to specify a private key file for SSH authentication, rather than use a password.  Does Deploy support private key files? (I couldn't find it in the documentation).

**Comment by mkloubert** [comment]
Yes, [sftp](https://github.com/mkloubert/vs-deploy/wiki/target_sftp) supports things like `privateKey` property.

**Comment by DavidA2014** [comment]
Thanks, privateKey worked for me.

**Comment by DavidA2014** [comment]
Would you expect to be able to use an environment variable in the private key path?

    "privateKey": "/%HOMEPATH%/Documents/ssh_keys/pc_priv.ppk"

That gives an error for me:
[FAILED: Error: ENOENT: no such file or directory, open 'C:\%HOMEPATH%\Documents\ssh_keys\pc_priv.ppk']
Finished with errors!

**Comment by mkloubert** [comment]
[Placeholders](https://github.com/mkloubert/vs-deploy/wiki/values) work in another way.

In your case, you have to use `homeDir`, which is pre-defined:

```json
  "privateKey": "${homeDir}/Documents/ssh_keys/pc_priv.ppk"
```

You also can import [environment variables](https://github.com/mkloubert/vs-deploy/wiki/environment_settings) and use your `HOMEPATH`, if it available for the process of your editor:

```json
  "privateKey": "${HOMEPATH}/Documents/ssh_keys/pc_priv.ppk"
```

**Comment by DavidA2014** [comment]
Thank you, that works fine.
