### ISSUE TITLE
[target_s3bucket] FAILED: CredentialsError: Missing credentials in config

### ISSUE THREAD

**Issue by matheusrufca** [mkloubert/vs-deploy#137]
I'm getting error when trying to deploy on S3 bucket.

Setting my credential type to` "file"`, what should I put on `config` prop?

**Deploy output:**
> Deploying '/dist/index.html' to 'index.html'... [FAILED: CredentialsError: Missing credentials in config]

**settings.json:**
```
{
  "settings": {},
  "folders": [{ "path": "D:\\Workspace\\sample" }],
  "deploy": {
    "packages": [
      {
        "name": "sample",
        "description": "sample",
        "files": [ "dist/**" ]
      }
    ],
    "targets": [
      {
        "type": "s3bucket",
        "name": "Sample",
        "bucket": "my-bucket.com.br",
        "credentials": {
          "type": "file",
          "config": {
            "credentials": {
              "filename": "./aws-credential.json"
            }
          }
        },
        "mappings": [{ "source": "/dist", "target": "/" }]
      }
    ]
  }
}
```

**Comment by mkloubert** [comment]
@matheusrufca 

The value of the `config` property is directly send to the constructor of the credential class (in that case `FileSystemCredentials`, s. [official documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/FileSystemCredentials.html)) of the [aws-sdk](https://www.npmjs.com/package/aws-sdk), so it must contain the (full) path of the file.

```json
{
    "targets": [
      {
        // ..

        "credentials": {
          "type": "file",
          "config": "/full/path/to/aws-credential.json"
        },

        // ..
      }
    ]
  }
}
```

Relative paths will not work as expected. I think they would be fully mapped to the working directory of the VSCode process or to the extension's directory, instead to workspace directory.

**Comment by matheusrufca** [comment]
Thanks @mkloubert! . It works.
I've tried put absolute path directly on config property because vs-code warns the following message when string is passed:

![image](https://user-images.githubusercontent.com/8710641/34271270-b62818da-e672-11e7-8258-116210ba9d21.png)

**Comment by mkloubert** [comment]
@matheusrufca 

Now I understand why you thought, that you have to put an object as setting value there. This makes it a little bit unclear, of course :-)

But it is only a minor mistake in the [package.json](https://github.com/mkloubert/vs-deploy/blob/master/package.json), Only something for the setting editor.

I will fix this. Thanks!

**Comment by matheusrufca** [comment]
@mkloubert in fact, 
putting a string on config was my first try, but i set workspace relative path and didn't work, then I tried a lot of variations, but as output message says that _credentials_ is missing, mostly of my tries was putting an `credentials` object inside of `config`.
But it's working now.
Great vscode extension, works perfectly for my needs.
