### ISSUE TITLE
App targeted deploying never ending

### ISSUE THREAD

**Issue by augustozanellato** [mkloubert/vs-deploy#138]
When I deploy a workspace to a custom script the deployment never ends, and the bottom bar always show (even multiple instances) of "Preparing deployment"

**Comment by mkloubert** [comment]
I have re-implemented the [app](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/target_app) in [new extension](https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-deploy-reloaded).

s. [your issue #8](https://github.com/mkloubert/vscode-deploy-reloaded/issues/8)
