### ISSUE TITLE
Confirmation before deployment via button

### ISSUE THREAD

**Issue by solid-pixel** [mkloubert/vs-deploy#141]
First off, let me tell you I love this extension **a lot**. Thank you very much!

I've added a button to deploy my files via SFTP, and while it's very convenient, it's also incredibly dangerous as with one single misclick you can easily overwrite your production site with no way of getting back your live files.

It would be great if you could add some sort of confirm() to the button in order to prevent accidental uploads.

Again thank you so much!

**Comment by mkloubert** [comment]
@solid-pixel @kairos03

**I have implemented the feature in version 0.34.1** of [vscode-deploy-reloaded](https://github.com/mkloubert/vscode-deploy-reloaded).

![demo20](https://user-images.githubusercontent.com/4951215/35823733-caabb070-0ab0-11e8-854f-7ae6a90da72b.gif)

**Comment by solid-pixel** [comment]
@mkloubert you're the man! Thank you so much.
I don't mind giving the -reloaded version a try as my setup is very basic.

What's the difference between the two? I don't understand.

Thanks!

**Comment by mkloubert** [comment]
@solid-pixel 

A cleaner API and a much better [multi workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces) support.

Most of the [settings](https://github.com/mkloubert/vscode-deploy-reloaded/wiki#settings--) are the same, so I think the change to the [new extension](https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-deploy-reloaded#review-details) should be easy.

The old extension has grown very fast the last year and I cannot not refactor the extension without crashing it in other parts, so I decided to refactor it.

[Issues and/or feature requests](https://github.com/mkloubert/vscode-deploy-reloaded/issues) are welcome :-)

**Comment by solid-pixel** [comment]
@mkloubert thanks for clarifying, makes perfect sense :) I will certainly post my ideas and concerns, take care!
