### ISSUE TITLE
Save before deploy

### ISSUE THREAD

**Issue by ondrejruzicka** [mkloubert/vs-deploy#143]
Hi, would it be possibe to have option, which checks if the file to deploy is saved? And if not it would be automatically saved and then deployed.

SFTP plugin for ST has the same here: https://wbond.net/sublime_packages/sftp/settings#setting-save_before_upload

Thanks

**Comment by mkloubert** [comment]
@ondrejruzicka 

This is a good feature for the new extension [vscode-deploy-reloaded](https://github.com/mkloubert/vscode-deploy-reloaded).

I will implement it there.

**Comment by mkloubert** [comment]
@ondrejruzicka 

**The feature is available since version 0.53.0 of [vscode-deploy-reloaded](https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-deploy-reloaded)** now ... it is activated by default, you do not need to setup anything.
