### ISSUE TITLE
How to deploy specific files, using button, on SFTP?

### ISSUE THREAD

**Issue by DavidA2014** [mkloubert/vs-deploy#145]
Hi Marcel,
Please will you help me with my settings confusion?  I want to deploy a specific file using SFTP.  I have this working with 'deployOnChange':

    "deploy": {

        "packages": [
            {
                "name": "My project",

                "deployOnChange": {
                    "files": [
                        "Source/NonDebug/MyAP.out"
                    ],
                    "useTargetList": true
                },

                "targets": [ "mypc" ]
            }
        ],

But I want to use a button instead of deployOnChange:

    "deploy": {

        "packages": [
            {
                "name": "My project",

                "button": {
                    "text": "Deploy to LedaPC",
                    "tooltip": "Click here to deploy to mypc...",

                    "targets": [ "My target" ]
                },

                "targets": [ "mypc" ]
            }
        ],

Using button, can I specify "files" to limit the file types transferred?

BTW should I move to deploy.reloaded?

Best regards
David

**Comment by DavidA2014** [comment]
Worked it out:

        "packages": [
            {
                "name": "LedaAP.out",
                "files": [
                    "Source/LedaAP_workbench/LedaAP/NonDebug/LedaAP.out"
                ],

                "button": {
                    "text": "Deploy 'LedaAP.out' to ledapc",
                    "tooltip": "Click here to deploy to ledapc...",
                    "targets": [ "LedaAP.out" ]
                },
            }
        ],

I would still be interested to know if I should move to deploy.reloaded?

**Comment by mkloubert** [comment]
@DavidA2014 

Yes, you can give the [new extension](https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-deploy-reloaded) a try.
If you install `vscode-deploy-reloaded`, you should uninstall or [deactivate that extension](https://code.visualstudio.com/docs/editor/extension-gallery#_disable-an-extension) first.

All required (basic) features (and more) are implemented there and running very stable.

If you have questions, suggestions and/or found bugs, you can [open an issue here](https://github.com/mkloubert/vscode-deploy-reloaded/issues).

Most of the settings should be compatible with the old extension, but you should [take a look at the wiki](https://github.com/mkloubert/vscode-deploy-reloaded/wiki) to check this out.

**Comment by DavidA2014** [comment]
Thank you
