### ISSUE TITLE
deployOnChange deploys files twice on change

### ISSUE THREAD

**Issue by unapieer** [mkloubert/vs-deploy#149]
When a change is detected, the files changed gets deployed TWICE to the server. Is this normal or do I need to setup my settings.json differently. 

```
{
    "deploy": {
        "packages": [
            {
                "name": "Test",
                "deployOnChange": {
                    "files": [
                        "**/_style/_css/*"
                    ],
                    "useTargetList": true,
                },
                "files": [
                    "**/*.html"
                ],
                "targets": [ "REMOTE" ],
            },
        ],

        "targets": [
            {
                "type": "ftp",
                "name": "REMOTE",
                "description": "REMOTE SERVER",
                "dir": "/dir/to/files",
                "host": "HOST", "port": 21,
                "user": "user", "password": "password"
            }
        ],
    }
}
```
OUTPUT PRINTOUT
```
Deploying file '/_style/_css/style.css.map' to '/_style/_css' ('REMOTE')... 
Deploying file '/_style/_css/style.css' to '/_style/_css' ('REMOTE')... 
Deploying file '/_style/_css/style.css.map' to '/_style/_css' ('REMOTE')... 
Deploying file '/_style/_css/style.css' to '/_style/_css' ('REMOTE')... 
[OK]
Finished
[OK]
Finished
[OK]
Finished
[OK]
Finished
```

**Comment by unapieer** [comment]
Figure out why, it is on my end. My sass complier is saving it twice when it AutoPrefix the CSS. 

On a related note.. Trying to get "timeToWaitBeforeActivateDeployOnChange" to work so it waits 2 second before deploying to let the complier to finish. It always fire right away.

**Comment by mkloubert** [comment]
@unapieer 

`timeToWaitBeforeActivateDeployOnChange` means that only at the beginning, after config has been (re-)loaded, the "deploy on change" feature will be deactivated for a specific time (in your case for 2000 ms).

This is not for each change event.

**Comment by mkloubert** [comment]
@unapieer 

btw.: I have implemented such a feature, what you had expected, in the new extension [vscode-deploy-reloaded](https://github.com/mkloubert/vscode-deploy-reloaded).

There you can define a setting, called `pauseFilesFor`, inside a [package](https://github.com/mkloubert/vscode-deploy-reloaded/wiki#packages-), which defines the time to wait before an auto deploy operation can be done for a file again:

In your case, that can look like that:

```json
{
    "deploy.reloaded": {
        "packages": [
            {
                "name": "CSS files",

                "files": [
                    "**/_style/_css/*"
                ],

                "deployOnChange": [ "REMOTE" ],

                "pauseFilesFor": 2000
            }
        ],

        "targets": [
            {
                "type": "ftp",
                "name": "REMOTE",
                "description": "REMOTE SERVER",
                "dir": "/dir/to/files",
                "host": "HOST", "port": 21,
                "user": "user", "password": "password"
            }
        ]
    }
}
```

Have a look at the [new wiki](https://github.com/mkloubert/vscode-deploy-reloaded/wiki) to check how to move migrate your [ftp](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/target_ftp) settings to the new extension.
