### ISSUE TITLE
Changelog population in vscode

### ISSUE THREAD

**Issue by asadsahi** [mkloubert/vs-deploy#15]
Hi @mkloubert 

With frequent changes and updates, is it possible to populae changelog tab when we view it in VS code?

![image](https://cloud.githubusercontent.com/assets/3470892/21453094/d0295614-c903-11e6-896c-fdd6b40e6054.png)

This makes it easier to quickly visualise the change and understand its usage.  With gifs it will even make it better to know the changes.

**Comment by mkloubert** [comment]
Done! Should now be visible in your extension tab and will be updated after each important release now:

![2016-12-23 17_50_42-extension_ deploy - visual studio code](https://cloud.githubusercontent.com/assets/4951215/21458645/927caaac-c938-11e6-8ebe-c3eff877a93c.png)

**Comment by asadsahi** [comment]
@mkloubert Thanks, :)
