### ISSUE TITLE
Deploy's Output pane log steals focus when it updates

### ISSUE THREAD

**Issue by MDBenson** [mkloubert/vs-deploy#159]
I have an issue, might be deploy or a bug in vs-code, but all indications are it's best taken up with extension developers. I have deploy-on-save enabled and every time I save while editing deploy works as intended but the Output Panel (which I have open for various debug messages from extensions I use, including vs-deploy) steals focus from the editor when I'm trying to type stuff, it's really frustrating. It's only cropped up very recently.

**Comment by MDBenson** [comment]
Possibly related? There's a suggestion for an API function that might help here:
https://github.com/Microsoft/vscode/issues/31474

**Comment by AlekVolsk** [comment]
Sep 2020, the problem is still relevant

**Comment by AlekVolsk** [comment]
Is it possible to add a setting in which in case of a successful deployment nothing will be displayed in output?

**Comment by MDBenson** [comment]
The reason thos hasn’t been resolved is the author has abandoned this project in favour of https://github.com/mkloubert/vscode-deploy-reloaded
I would suggest upgrading, it is a lot more usable and is updated frequently.
