### ISSUE TITLE
end of central directory record signature not found

### ISSUE THREAD

**Issue by Huachao** [mkloubert/vs-deploy#20]
when downloading this extension, vscode prompts error 'end of central directory record signature not found'

**Comment by mkloubert** [comment]
I currently have released **Version 4.12.0**.

**Search for `vs-deploy` in your extension tab and try install it again.**

Maybe you have to uninstall it, before you can reinstall it.

In that case keep sure that there are no `%USERPROFILE%\.vscode\extensions\mkloubert.vs-deploy-*` directories anymore

**Comment by Huachao** [comment]
thanks
