### ISSUE TITLE
Prevent deploying twice at the same time

### ISSUE THREAD

**Issue by unional** [mkloubert/vs-deploy#21]
Currently if [ctrl+alt+w] is pressed twice, two deployments will execute at the same time.
It would be best if the second deployment is a different package/target or at least ask the user consent to this stupid action. 😏

**Comment by mkloubert** [comment]
**Implemented since version 4.19.1.**

![deploy-already-running-example](https://cloud.githubusercontent.com/assets/4951215/21719324/6c2d7db4-d41d-11e6-9884-f95db8de307c.gif)

**Comment by unional** [comment]
Saw it working.
However, can we do this only for workspace sync?
Since there is some delay and latency involved when deploying files, quicking saving the same file twice would trigger this.

**Comment by mkloubert** [comment]
Sorry for my late post, but **I have deactivated the feature for single files since version 4.20.1**.

The warn popups still appear when you try to deploy a workspace several times.
