### ISSUE TITLE
Show "Indexing..." or "Calculating..."

### ISSUE THREAD

**Issue by unional** [mkloubert/vs-deploy#23]
When there are lots of files to deploy, it takes 8-9 seconds before "Deploying package '<package>' to '<target>'..." appears.

It would be nice to add "Indexing..." or "Calculating..." is the status bar once the [ctrl+alt+w] is pressed.

**Comment by mkloubert** [comment]
**Implemented since version 4.18.0.**

![prepare-deploy-msg-example](https://cloud.githubusercontent.com/assets/4951215/21715661/28916168-d406-11e6-970e-c1c51a60f1ac.gif)

**Comment by unional** [comment]
Just tested, still not working. When it is in "Deploying..", clicking on it doesn't work.

**Comment by unional** [comment]
^ comment on the wrong issue.

Saw this working with the "preparing deployment..." 🍻
