### ISSUE TITLE
Use status bar instead of infoMessageWindow for deployOnSave

### ISSUE THREAD

**Issue by unional** [mkloubert/vs-deploy#26]
This would help making `deployOnSave` more transparent. 🌷

**Comment by mkloubert** [comment]
**Deployed since version 4.18.0.**

![after-deploy-status-button-example](https://cloud.githubusercontent.com/assets/4951215/21716011/0f2e682c-d408-11e6-9dcc-597aa04a3176.gif)

You have to set `showDeployResultInStatusBar` and `showPopupOnSuccess` properties:

```json
{
    "deploy": {
        "showDeployResultInStatusBar": true,
        "showPopupOnSuccess": false,

        // ...
    }
}
```

**Comment by unional** [comment]
Confirmed working! 👍
