### ISSUE TITLE
command 'extension.deploy' not found

### ISSUE THREAD

**Issue by nopower0** [mkloubert/vs-deploy#28]
When deploying to a sftp target, "command 'extension.deploy' not found" message is shown.  And I cannot find the Quick Deploy button even if I have "button" section configured.

**Comment by gaochangyu** [comment]
Same problem happened  to me.

**Comment by hkm-mo** [comment]
So me too

**Comment by mkloubert** [comment]
What versions of VSCode and the extenstion do you use?

**Comment by mkloubert** [comment]
Have you tried to reinstall the extension?

**Comment by hkm-mo** [comment]
I have reinstalled the extension. But the issue still exist. 
My installed version is VSCode 1.8.1(OSX) + Deploy 5.3.1

**Comment by mkloubert** [comment]
Have you checked the debug console (CTRL + SHIFT + Y)?

Has pop uped an error message at the top of VSCode?

**Comment by gaochangyu** [comment]
I have Vscode 1.8.1 windows 10 deploy 5.3.1.
It pops up saying "command extension.deploy not found".

**Comment by qrti** [comment]
same problem here, command extension.deploy not found,
win10, vscode 1.8.1, deploy 5.3.1

**Comment by lvbeck** [comment]
same problem, auto deployment on file save stop working after update to 5.3.1,
when use CTRL + ALT + F, show error: command extension.deploy not found
win10, vscode 1.8.1, deploy 5.3.1

**Comment by mkloubert** [comment]
Now I have the same problem.

The `package.json` file seems to be corrupt.

As fast workarround: Download the previous version of [package.json][https://raw.githubusercontent.com/mkloubert/vs-deploy/3eca79e577b4cd9939508f3a0d0b79d75b943f1a/package.json] file
and replace it with the version in your extension folder (`%USERPROFILE%\.vscode\extensions\mkloubert.vs-deploy-5.3.1`) and run VSCode again.

I will fix this in about 9 hours when I am at home again.

**Comment by mkloubert** [comment]
I FOUND THE BUG!

Currently there are missing dependencies for [mysql](https://www.npmjs.com/package/mysql) and [mssql](https://www.npmjs.com/package/mssql) modules.

AS FAST WORKARROUND: Edit the `package.json` file in your extension directory (`%USERPROFILE%\.vscode\extensions\mkloubert.vs-deploy-5.3.1`), go to the bottom and add these references to `dependencies`:

```json
{    
    // ...
    
	"dependencies": {
		"aws-sdk": "^2.7.19",
		"azure-storage": "^1.4.0",
		"fs-extra": "^1.0.0",
		"ftp": "^0.3.10",
		"glob": "^7.1.1",
		"i18next": "^4.1.4",
		"mime": "^1.3.4",
		"moment": "^2.17.1",
        
        "mysql": "^2.12.0",
        "mssql": "^3.3.0",
        
		"node-uuid": "^1.4.7",
		"node-zip": "^1.1.1",
		"nodemailer": "^2.7.0",
		"ssh2-sftp-client": "^1.0.5"
	},
    
    // ...
}

```

After that: Open the terminal / command line, go to the extension directory and run

```bash
npm install

```

to install the missing modules. Then start VSCode again.


As I said, I will fix this in about 8 hours.

**Comment by lvbeck** [comment]
thanks @mkloubert , but the fast workaround still not work for me, the pop up error message disappeared.

**Comment by mkloubert** [comment]
**OK, the bug should be fixed since version 5.3.2.**

Do the following steps:

* uninstall the extension (`CTRL + SHIFT + X`, `Deploy`)
* close VSCode
* keep sure to have no existing extension directories (`%USERPROFILE%\.vscode\extensions\mkloubert.vs-deploy-`)
* start VSCode
* install the extension (`CTRL + SHIFT + X` and search for `vs-deploy`)

Please let me know if anything now works.

@lvbeck @qrti @gaochangyu @nopower0 @hkm-mo

**Comment by nopower0** [comment]
Thank you so much! I've tried with your latest steps and it works!

**Comment by lvbeck** [comment]
@mkloubert 5.4.1 update still break.

I did exactly as you said, uninstall, close, check legacy folder, restart VS and reinstall extension but didn't help...

no auto deployment as well as CTRL + ALT + F command. and nothing is there in the debug console.

**Comment by lvbeck** [comment]
I used to deploy my files to a SFTP server, this works perfectly in version 4.x , afte I update to 5.x, everthing stop working.

I notice a changes related to SFTP in version 4.21.0, maybe the bug is introduce from this release?

**Comment by mkloubert** [comment]
@lvbeck When I am testing, it works and I can deploy.

Can you post an example of your `settings.json` here?

**Comment by lvbeck** [comment]
@mkloubert here is my settings.json:
```
{
    "deploy": {
        "packages": [
            {
                "name": "My App 1.0.0",
                "description": "My App 1.0.0",
                "files": [
                    "**/*.php",
                    "**/*.js",
                    "**/*.css",
                    "**/*.html",
                    "/*.json"
                ],
                "exclude": [
                    "tests/**"
                ],
                "deployOnSave": true
            }
        ],       
        "showPopupOnSuccess": true,
        "targets": [
            {
                "type": "sftp",
                "name": "My App folder",
                "description": "A SFTP folder",
                "dir": "/var/www/myapp",
                "host": "www.example.com", "port": 22,
                "user": "****", "password": "******"
            }
        ]
    },    
    "php.validate.executablePath": "C:/PHP/php.exe",
    "editor.fontSize": 12
}
```

**Comment by lvbeck** [comment]
@mkloubert now it works under certain circumstances, after I disabled all other vscode extensions except deploy and restart vscode, is it possible that some extension conflicts with deploy?

**Comment by mkloubert** [comment]
@lvbeck No, the extension has no dependencies to other extensions.
