### ISSUE TITLE
ssh-agent

### ISSUE THREAD

**Issue by LukasDrude** [mkloubert/vs-deploy#36]
When deploying to sftp, I have to add my private key passphrase to the config file in plain text, according to [your documentation](https://github.com/mkloubert/vs-deploy/wiki/target_sftp).

You may elaborate on using the internal ssh-agent or any other means of avoiding to store the password in plain text.

My solution so far is to remove the passphrase from the private key as is done in this [Q&A](http://stackoverflow.com/questions/112396/how-do-i-remove-the-passphrase-for-the-ssh-key-without-having-to-create-a-new-ke).

**Comment by mkloubert** [comment]
@LukasDrude 

Thank you very much for the issue and sorry for the late answer, but now I found the time to implement a feature that supports ssh agents.

**The feature is available since version 5.28.0** and uses the [client settings](https://github.com/mscdex/ssh2#client-methods) of [ssh2 module](https://www.npmjs.com/package/ssh2), I am indirectly using with [ssh2-sftp-client](https://www.npmjs.com/package/ssh2-sftp-client).

At the [wiki](https://github.com/mkloubert/vs-deploy/wiki/target_sftp), you can see how to use it (`agent` and `agentForward` properties).

Please give me a feedback if that works for you and if you think that there are also things to improve.

**Comment by LukasDrude** [comment]
I updated the plugin to 5.29.0 on OSX.

I added (and unlocked with my passphrase) my private key with `ssh-add`. Now `ssh-add -L` shows the private key in a terminal session.

My configuration now looks like this:
```
                "privateKey": "/Users/****/.ssh/id_rsa",
                "agent": "/usr/bin/ssh-agent",
                "agentForward": true
```

But I still get this two error messages:
```
Could not deploy files (2): Error: Encrypted private key detected, but no passphrase given
Could not deploy files to '****': Error: Encrypted private key detected, but no passphrase given
```

It seems like it is ignoring the agent settings. Otherwise I would expect errors in this sense: "Connected to agent. Agent empty." or similar.

**Comment by mkloubert** [comment]
Have you tried to remove the the `privateKey` property?

I think [ssh2](https://github.com/mscdex/ssh2#client-methods) will use the private key file instead of the agent, because it seems to prioritize the settings.

**Comment by LukasDrude** [comment]
With this configuration:
```
                // "privateKey": "/Users/***/.ssh/id_rsa"
                "agent": "/usr/bin/ssh-agent",
                "agentForward": true
```
I encounter the following errors:
```
Could not deploy files (2): Error: connect ENOTSOCK /usr/bin/ssh-agent
Could not deploy files to 'ntpc4': Error: connect ENOTSOCK /usr/bin/ssh-agent
```

Just to make sure, `ls -lha /usr/bin/ssh-agent` shows:
```
-rwxr-xr-x  1 root  wheel   1.4M May  5  2016 /usr/bin/ssh-agent
```

So it is accessible and executable by the user.

**Comment by mkloubert** [comment]
@LukasDrude 

According to [that issue](https://github.com/mkloubert/vs-deploy/issues/63), it should be possible to access an environment variable like `SSH_AUTH_SOCK` via a [placeholder](https://github.com/mkloubert/vs-deploy/wiki/values), which contains the path to the agent's socket, what can be written to `agent` settings of [sftp](https://github.com/mkloubert/vs-deploy/wiki/target_sftp) targets now.

```json
"deploy": {
    "values": [
        {
            "name": "SSH_AUTH_SOCK",
            "type": "env"
        }
    ],

    "targets": [
        {
            "name": "My SFTP target",

            // ...

            "agent": "${SSH_AUTH_SOCK}"
        }
    ]
}
```
