### ISSUE TITLE
Feature request: folder mapping

### ISSUE THREAD

**Issue by unional** [mkloubert/vs-deploy#4]
I was using WebStorm for development and want to switch to VSC.
This is the last feature I need to complete the transition.

Currently, in WebStorm, I setup folder mapping to sync different locations of the files to a different site.

For example:

```
- scripts
- ui
  - src  // VSCode is opened here, because it doesn't work with multiple folders yet.
  - debug
```

is mapped to:
```
- root
  - unional
    - scripts (mapped to scripts)
    - core (mapped to ui/src)
    - debug (mapped to ui/debug)
```

The local folder structure is defined by the repository so I can't change it. 😢

**Comment by mkloubert** [comment]
Great feature request! 👍 

**I have implemented this** in version 3.0 **which is now available**! :D

You have to define the list of mappings in a target (an example for SFTP):

```json
{
    "deploy": {
        "targets": [
            {
                "type": "sftp",
                "name": "My SFTP folder",
                "description": "A SFTP folder",

                "mappings": [
                    {
                        "source": "ui/src",
                        "target": "core"
                    },
                    {
                        "source": "ui/debug",
                        "target": "debug"
                    }
                ],

                "dir": "/my_package_files",
                "host": "localhost", "port": 22,
                "user": "tester", "password": "password",
            }
        ]
    }
}
```

This works for:
- [FTP](https://github.com/mkloubert/vs-deploy/wiki/target_ftp)
- [HTTP](https://github.com/mkloubert/vs-deploy/wiki/target_http)
- [Local](https://github.com/mkloubert/vs-deploy/wiki/target_local)
- [Mail](https://github.com/mkloubert/vs-deploy/wiki/target_mail)
- [Remote](https://github.com/mkloubert/vs-deploy/wiki/target_remote)
- [SFTP](https://github.com/mkloubert/vs-deploy/wiki/target_sftp)
- [ZIP](https://github.com/mkloubert/vs-deploy/wiki/target_zip)

**Comment by unional** [comment]
Great. I am trying it with SFTP and it seems like it is very slow. Do you know what trick WebStorm does to make it so fast?

**Comment by unional** [comment]
Nevermind. Seems like it is ok now. Will see how long it takes. 🌷

**Comment by mkloubert** [comment]
I optimized the deploying of files to (S)FTP since version 3.0.

In earlier version, a new connection was opened for each file. This was really slow.

Now there is only one connection opened for one operation. Even if you have 1000 of files or only one.

That makes it a lot faster.
