### ISSUE TITLE
Feature Request: Download from remote

### ISSUE THREAD

**Issue by realee94** [mkloubert/vs-deploy#40]
Hello, first of all thanks for the amazing plugin.

I know this is meant to deploy to a server, but I would love a feature to pull the files from the mapped directories.

I hope you like the idea and can/will implement it. Thanks!

**Comment by mkloubert** [comment]
@realee94 

Thanks for the feature request!

This is a good reason to start a v6 branch ... but I will implement and release this step by step (target by target).

**What targets you would like to be implemented first?**

**Comment by realee94** [comment]
@mkloubert 

Thanks for your answer!

FTP and SFTP would be the most useful for me personally.

Thank you again.

**Comment by mkloubert** [comment]
@realee94 @pyr0hu

Mission accompilshed ... **Version 6.0.0 has been released!** :-)

![demo6](https://cloud.githubusercontent.com/assets/4951215/23817015/66830c62-05f0-11e7-99a1-500d71611637.gif)

You are now able to pull from the following targets:

* [SFTP](https://github.com/mkloubert/vs-deploy/wiki/target_sftp)
* [FTP](https://github.com/mkloubert/vs-deploy/wiki/target_ftp)
* [DropBox](https://github.com/mkloubert/vs-deploy/wiki/target_dropbox)
* [Local or shared network folders inside a LAN](https://github.com/mkloubert/vs-deploy/wiki/target_local)
* [ZIP files](https://github.com/mkloubert/vs-deploy/wiki/target_zip)
* [Amazon AWS S3 buckets](https://github.com/mkloubert/vs-deploy/wiki/target_s3bucket)
* [Azure blob storages](https://github.com/mkloubert/vs-deploy/wiki/target_azureblob)
* [External Node.js based scripts](https://github.com/mkloubert/vs-deploy/wiki/target_script)
* [REST APIs](https://github.com/mkloubert/vs-deploy/wiki/target_api)

The shortcuts are:

* `CTRL+ALT+P, F` (Pull current file / folder)
* `CTRL+ALT+P, W` (Pull files of package)

**Comment by realee94** [comment]
Wow, amazing!

Thank you and keep up the good work man! :)
