### ISSUE TITLE
Rename file / move it during copy

### ISSUE THREAD

**Issue by sebastus** [mkloubert/vs-deploy#41]
With my project the source folder structure and target folder structure aren't identical. And I may want to rename the file during the copy. Is this possible?

**Comment by mkloubert** [comment]
@sebastus 

You are able to [map your local folders to other ones](https://github.com/mkloubert/vs-deploy/issues/4#issuecomment-267605754).

**Comment by sebastus** [comment]
Great solution for moving the file to a different folder structure. Thanks.
