### ISSUE TITLE
Feature Request: Feedback/response about deployment

### ISSUE THREAD

**Issue by realee94** [mkloubert/vs-deploy#43]
Hello,

I have a new feature request, but I'm not so sure if it is possible at all. Yesterday I have ran into a slight error. I was setting up my own server and I screwed up the permissions, etc. Long story short, plugin said deployment was successful, but in reality, my files never got uploaded in the folder because my FTP user didn't have write permission.

I would love to get an error with a message explaining the issue, so I could figure out what is the problem quicker. It is a minor issue, but still, I think it would be nice.

However, I'm not sure it is possible through Javascript but I thought asking doesn't hurt.

Thanks and looking forward to your answer!

**Comment by mkloubert** [comment]
@realee94 

For FTP uploads I use the [ftp](https://www.npmjs.com/package/ftp) module, which returns error objects in the callbacks when an error occurrs.

It looks like the server does not report errors (in that case).

**What server software do you use and does this also happens when you use another FTP client?**

**Comment by realee94** [comment]
@mkloubert 

I have a basic cloud setup with Ubuntu 16.10 and Apache web-server, Proftpd FTP server and the usual stuff (Mysql, php, etc). I didn't try it with anything else, because I quickly realized what is the issue. Once I have time I will check out other FTP clients too.

Any suggestion which ones to try with and see what error they throw?

**Comment by mkloubert** [comment]
[WinSCP](https://winscp.net/) or [ftp](https://www.howtoforge.com/tutorial/how-to-use-ftp-on-the-linux-shell/) on Linux / Mac.

**Comment by mkloubert** [comment]
@realee94 

I think I found the bug.

While I am implementing the [download feature](https://github.com/mkloubert/vs-deploy/issues/40), I found out that the extension is the one that reports wrong results.

I think today or tomorrow you will get the bug fix including the new download / pull feature :-)

**Comment by realee94** [comment]
@mkloubert 

Sorry for not responding but I didn't have time to check it out.

You're doing god's work man! I can't wait for the update. ;) Keep it up!
👍

**Comment by mkloubert** [comment]
@realee94 

**Should be fixed since version 6.0.0.**
