### ISSUE TITLE
How to use Command?

### ISSUE THREAD

**Issue by sebastus** [mkloubert/vs-deploy#47]
I put your sample command into my settings file and copied the .js file into .vscode directory. I restarted vscode. I don't see a button and I don't see the command name in the command list. Are there some steps missing?

**Comment by mkloubert** [comment]
Relative paths, that are used for the extension, are relative to the workspace, not to the current file.

**Comment by mkloubert** [comment]
@sebastus 

Have you used the command ID `mkloubert.mycommand` in another context inside your `settings.json`?

Maybe changing the ID to something like `mkloubert.mycommand2` can help (and moving the `.js` file to the root of your workspace).

**Comment by sebastus** [comment]
Putting the file into the right place fixed me up. I wanted to use that technique to run a packaging script and had some trouble with the Node code bits. Gave up the effort in favor of your "batch" and "app" targets. I save the file, then the app runs a .cmd that runs 7zip to tar/gz the solution.
