### ISSUE TITLE
SFTP SSH Key

### ISSUE THREAD

**Issue by anxious77** [mkloubert/vs-deploy#5]
Connection via SFTP with SSH Key Authentification would be great!

**Comment by mkloubert** [comment]
Great! 👍 

**I have implemented** the feature in version 3.0 **that is now available!**

Look a the [at the wiki page](https://github.com/mkloubert/vs-deploy/wiki/target_sftp) (on the bottom where the table is), that shows what options you have to define:

```json
{
    "deploy": {
        "targets": [
            {
                "type": "sftp",
                "name": "My SFTP folder",
                "description": "A SFTP folder",

                "dir": "/my_package_files",
                "host": "localhost", "port": 22,
                
               "privateKey": "the/path/to/your/file.key",
               "privateKeyPassphrase": "a_passphrase_if_needed"
            }
        ]
    }
}
```

**Comment by enly1** [comment]
FYI - I'm sure you're waiting for positive feedback here, so I can confirm that the privatekey option is working, althought its a key that has no passphrase (yes I know).

**Comment by mkloubert** [comment]
Thank, @enly1! :-)

**Comment by pcdevil** [comment]
Hello, thank you the implementation, it just works for me too.

Please consider adding to the Wiki as well!
