### ISSUE TITLE
[FEHLER] Deployer.reloadPlugins(2): Error: Cannot find module 'gulp'

### ISSUE THREAD

**Issue by xGabba** [mkloubert/vs-deploy#50]
Hello,

additional to this ERROR I also have the two following problems:

- As antoher user already mentioned, it is not possible to cancle if you for example insert wrong ftp/sftp login data. After I canceled, it took 10 minutes after I rebooted VS code.
- I insert the following settings:
`"deploy": {
        "packages": [
            {
                "name": "Version 2.3.4",
                "description": "Package version 2.3.4",
                "files": [
                    "**"
                ],
                "deployOnSave": true
            }
        ],
        "targets": [
            {
                "type": "ftp",
                "name": "host.de/wp_content/themes/living4it-theme/",
                "description": "A FTP folder",

                "dir": "/wp_content/themes/living4it-theme",
                "host": "host", "port": 21,
                "user": "user", "password": "pwd"
            }
        ]
    }`
After I saved a file it notifies that the file was deployed and in the console its written from ... to .. and at the ending [OK]. But on the host the file wasn't changed. One supposition is, that this happens because of a certificate which gets not accepted or something like this?

Greetings

**Comment by mkloubert** [comment]
@xGabba 

**I have released a new version 7.14.0**, where:

* `gulp.js` should be removed
* a FTP connection is closed explicit, when you start cancelling

You are also now able to set the `connTimeout`, `pasvTimeout` and `keepalive` properties in a [FTP target](https://github.com/mkloubert/vs-deploy/wiki/target_ftp).

**Comment by xGabba** [comment]
@mkloubert 

- works great
- It's still pending when I'm using wrong login data. I `"connTimeout": 3000, "pasvTimeout": 3000`
And I can't pull or upload a file with right incredients. If I try to pull a file from host, then everything works apart form that the file is empty.

**Comment by mkloubert** [comment]
@xGabba 

**I have released version 7.15.0 with a new setting for [ftp targets](https://github.com/mkloubert/vs-deploy/wiki/target_ftp).**

Set the `engine` property to `jsftp`:

```json
{
    "deploy": {
        "targets": [
            {
                "type": "ftp",

                "engine": "jsftp"
            }
        ]
    }
}
```

This should fix the issue with pulling files, but that means that some settings have no effect, because the new engine does not support that.

**Comment by xGabba** [comment]
- Now I'm getting an error, that the incredients are wrong (Error: 530) great!
- I found the real issue because the update didn't work. My dir path was wrong, the "_" should be a "-". Everything works with "ftp" and "jsftp". The pull is working too!

**Comment by mkloubert** [comment]
@xGabba

Kein Problem! ;)
