### ISSUE TITLE
Quick deploy button text doesn't change to settings.deploy.button.text

### ISSUE THREAD

**Issue by tkafka** [mkloubert/vs-deploy#51]
Here's a part of my `deploy` in settings.json:

    "deploy": {
        "button": {
            "enabled": true,
            "text": "→ airflow.reporter.dev",
            
            "packages": [ "airflow.reporter.dev/dags" ]
        },
        ...

However, even after restart of VS code, the quick deploy button still shows 'Quick deploy!'.

This seems like a bug to me, I expected the button to show the value of `settings.deploy.button.text`, is this right?

(but still, vs-deploy is an amazin piece of work, thanks! :))

**Comment by mkloubert** [comment]
@tkafka

Thats right, it is a bug.

I will fix it this evening when I am at home (I think about 6 hours).

**Comment by mkloubert** [comment]
@tkafka 

Should be fixed since version 7.14.1.

**Comment by tkafka** [comment]
Awesome, thanks! ❤️
