### ISSUE TITLE
Active mode

### ISSUE THREAD

**Issue by dannielarriola** [mkloubert/vs-deploy#53]
How can I activate active mode for ftp conections?

**Comment by mkloubert** [comment]
@dannielarriola 

Unfortunately none of the supported modules does seem to support this directly.

**BUT:** The [jsftp](https://github.com/sergi/jsftp) seems to be able to send raw commands, what means that it should be possible to send something like `PASV off` or `passive` to the server.

I will take a look, if it makes sense to define one or more custom FTP commands, which will be executed after a connection has been established...

**Comment by mkloubert** [comment]
@dannielarriola 

Sorry for the late post.

I am not sure if it helps: but **I have released version 8.15.1** that is now able to [execute raw FTP commands](https://github.com/mkloubert/vs-deploy/wiki/target_ftp#execute-commands-on-server) with the help of `beforeUpload`, `closing`, `connected` and `uploaded` settings.

You can try to execute `ABOR`, `PASV off` or `passive` command before you upload a file, but both engines ([ftp](https://github.com/mscdex/node-ftp) and [jsftp](https://github.com/sergi/jsftp)) seem only support passive mode.

**Comment by dannielarriola** [comment]
@mkloubert , 
Ok, I m going to try that, thanks for helping
