### ISSUE TITLE
Detect SCSS compilation

### ISSUE THREAD

**Issue by jaredmalcolm** [mkloubert/vs-deploy#54]
Currently, I'm using a watch task and an SFTP deployment plugin for Gulp to compile/deploy the CSS that Gulp is generating. 

Is there a way that Deploy could detect that the files were regenerated and handle the deploy portion of that?

**Comment by mkloubert** [comment]
@jaredmalcolm 

You can use "deploy on change" feature for that: https://github.com/mkloubert/vs-deploy/wiki/deploy_on_change
