### ISSUE TITLE
[Request][Feature] Deploy to 1 target with multiple destination dirs

### ISSUE THREAD

**Issue by CasperPas** [mkloubert/vs-deploy#55]
Currently I have a sandbox server with multiple web environments (for many testers). Now I need to define multiple targets with the same login info for each folder and deploy it separately. Something like this:

```json
{
    "type": "sftp",
    "name": "Sandbox Server",
    "description": "A SFTP folder",
    "dirs": [
        "/home/mgsys/dev_envs/dev2",
        "/home/mgsys/dev_envs/dev3",
        "/home/mgsys/dev_envs/dev27"
    ],
    "host": "sandbox_srv", "port": 22,
    "user": "mgsys",
    "privateKey": "/users/admin/.ssh/id_rsa"
}
```

**Comment by mkloubert** [comment]
@CasperPas 

Thanks for the feature request!

**I will implment this in version 8.0 with a new target type. I think that it will be finished until the weekend.**

Meanwhile you can try to use a [batch](https://github.com/mkloubert/vs-deploy/wiki/target_batch) target: 

```json
[
    {
        "type": "batch",
        "name": "Sandbox Server",
        "description": "A SFTP folder",
        "targets": [
            "Sandbox Server (dev2)",
            "Sandbox Server (dev3)",
            "Sandbox Server (dev27)"
        ]
    },

    {
        "type": "sftp",
        "name": "Sandbox Server (dev2)",
        "description": "Deploys to dev2 folder",
        "dir": "/home/mgsys/dev_envs/dev2",
        "host": "sandbox_srv", "port": 22,
        "user": "mgsys",
        "privateKey": "/users/admin/.ssh/id_rsa",

        "isHidden": true
    },

    {
        "type": "sftp",
        "name": "Sandbox Server (dev3)",
        "description": "Deploys to dev3 folder",
        "dir": "/home/mgsys/dev_envs/dev3",
        "host": "sandbox_srv", "port": 22,
        "user": "mgsys",
        "privateKey": "/users/admin/.ssh/id_rsa",

        "isHidden": true
    },

    {
        "type": "sftp",
        "name": "Sandbox Server (dev27)",
        "description": "Deploys to dev27 folder",
        "dir": "/home/mgsys/dev_envs/dev27",
        "host": "sandbox_srv", "port": 22,
        "user": "mgsys",
        "privateKey": "/users/admin/.ssh/id_rsa",

        "isHidden": true
    }
]
```

I know that this is not a very "handy" solution. This is why I will implement the new target type.

BTW: `isHidden` property means, that the underlying targets are not shown in the GUI. If you want to show then, simply remove them or set them to `(false)`.

**Comment by CasperPas** [comment]
that's awesome. you're the best. I'm looking forward to that 👍 😉

**Comment by mkloubert** [comment]
@CasperPas 

**I released version 8.0.0 with a new target type, called [each](https://github.com/mkloubert/vs-deploy/wiki/target_each).**

![aufnahme_2017_04_15_04_07_55_309](https://cloud.githubusercontent.com/assets/4951215/25059984/d49c3d6a-2191-11e7-8fc0-1c75d0ace777.gif)

Your settings should look like that:

```json
{
    "deploy": {
        "targets": [
            {
                "name": "Sandbox Server",
                "type": "each",

                "from": [
                    "/home/mgsys/dev_envs/dev2",
                    "/home/mgsys/dev_envs/dev3",
                    "/home/mgsys/dev_envs/dev27"
                ],

                "to": [ "dir" ],

                "targets": [ "Template of Sandbox Server" ]
            },

            {
                "name": "Template of Sandbox Server",
                "type": "sftp",

                "host": "sandbox_srv", "port": 22,
                "user": "mgsys",
                "privateKey": "/users/admin/.ssh/id_rsa",

                "isHidden": true
            }
        ]
    }
}
```

What happens is:

* the `Sandbox Server` target interates over the 3 values in `from`
* it sends all these values to "real" target `Sandbox Server template`
* as defined in `to` property of `Sandbox Server`, the values are written to `dir` setting of `Sandbox Server template` (this is why you do not see a defined `dir` here, because `Sandbox Server` does this job for you)

You also can do this with any other properties, like the `host`, e.g.:

```json
{
    "deploy": {
        "targets": [
            {
                "name": "Sandbox Server",
                "type": "each",

                "from": [
                    "dev2.example.com",
                    "dev3.example.com",
                    "dev27.example.com"
                ],

                "to": [ "host" ],

                "targets": [ "Template of Sandbox Server" ]
            },

            {
                "name": "Template of Sandbox Server",
                "type": "sftp",

                "dir": "/home/mgsys/dev_env",
                "user": "mgsys",
                "privateKey": "/users/admin/.ssh/id_rsa",

                "isHidden": true
            }
        ]
    }
}
```

BTW: I also added another feature, that makes it possible to quickly access examples, templates, wiki articles and other resource ... simply press `F1` and select `Deploy: Open example / template` command:

![Screenshot Template example](https://raw.githubusercontent.com/mkloubert/vs-deploy/master/img/demo8.gif)

More information can be found [here](https://github.com/mkloubert/vs-deploy/issues/56).

**Comment by CasperPas** [comment]
Wow, you're awesome! I've just updated and it works great.
However, I also want to ask that, do you feed those each values to each "targets" then each time, it needs to establish the connection everytime? ex, if we have 3 "from" and 2 "targets" => 6 different sessions?

**Comment by mkloubert** [comment]
Thats right. This is what you have to keep in mind.

The job of this target type has to be as simple and generic as possible.

That means it has to work with all target types, not only with the existing onces, even with targets that will be implemented in the future and with targets that do not need a session or network connection, like [local](https://github.com/mkloubert/vs-deploy/wiki/target_local).

On the other hand [the "each"](https://github.com/mkloubert/vs-deploy/wiki/target_each) cannot decide if "dir" or "host" setting properties are things that can be "put" into one session or not.

It only works as a simple [for loop](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) with all its "consequences".

**Comment by mkloubert** [comment]
@CasperPas 

This might be also interesting for you:

**With version 8.7.0 I released a similar target type, called [map](https://github.com/mkloubert/vs-deploy/wiki/target_map):**

```json
{
    "deploy": {
        "targets": [
            {
                "name": "Sandbox Server",
                "type": "map",

                "from": [
                    {
                        "dir": "/home/mgsys/dev_envs/dev2"
                    },
                    {
                        "dir": "/home/mgsys/dev_envs/dev3"
                    },
                    {
                        "dir": "/home/mgsys/dev_envs/dev27"
                    }
                ],

                "targets": [ "Template of Sandbox Server" ]
            },

            {
                "name": "Template of Sandbox Server",
                "type": "sftp",

                "host": "sandbox_srv", "port": 22,
                "user": "mgsys",
                "privateKey": "/users/admin/.ssh/id_rsa",

                "isHidden": true
            }
        ]
    }
}
```

As you can see: The difference is, that you can define a list of value repositories, which contain a list of properties (and their values) that should be written to `Template of Sandbox Server`.
