### ISSUE TITLE
Warn user before uploading if remote file is newer than local file.

### ISSUE THREAD

**Issue by ryanpcmcquen** [mkloubert/vs-deploy#58]
Is there a way to do this? It would be a killer feature for me and my team.

**Comment by mkloubert** [comment]
@ryanpcmcquen 

Great feature request!

What targets do you use?

**Comment by ryanpcmcquen** [comment]
Thank you! We are using `SFTP`.

**Comment by mkloubert** [comment]
@ryanpcmcquen 

**I released version 8.9.0 with a new [target](https://github.com/mkloubert/vs-deploy/wiki#targets-) setting, called `checkBeforeDeploy`:**

![Demo check for newer files](https://raw.githubusercontent.com/mkloubert/vs-deploy/master/img/demo9.gif)

```json
{
    "deploy": {
        "targets": [
            {
                "type": "sftp",

                // ...

                "checkBeforeDeploy": true
            }
        ]
    }
}
```

This works for

* [azureblob](https://github.com/mkloubert/vs-deploy/wiki/target_azureblob)
* [dropbox](https://github.com/mkloubert/vs-deploy/wiki/target_dropbox)
* [ftp](https://github.com/mkloubert/vs-deploy/wiki/target_ftp)
* [local](https://github.com/mkloubert/vs-deploy/wiki/target_local)
* [s3bucket](https://github.com/mkloubert/vs-deploy/wiki/target_s3bucket)
* [script](https://github.com/mkloubert/vs-deploy/wiki/target_script)
* [sftp](https://github.com/mkloubert/vs-deploy/wiki/target_sftp)
* [test](https://github.com/mkloubert/vs-deploy/wiki/target_test)
* [zip](https://github.com/mkloubert/vs-deploy/wiki/target_zip)

targets.

**Comment by iFarmGolems** [comment]
Hey, 

Great feature!

Could you also make it work with "deployOnSave" (SFTP) ? 

When I use it like that, It won't ask and just uploads the file, even though the file on the server is different than mine.

**Comment by mkloubert** [comment]
@iFarmGolems 

The feature works as expected.

It checks only for newer files. If you save a file, your timestamp is the youngest and the timestamp on the server becomes the older one.

**Comment by ryanpcmcquen** [comment]
Amazingly fast work!

I do see where @iFarmGolems is coming from though. Maybe a separate option where it compares the remote timestamp to the timestamp of the file _before_ save would be useful for that scenario.

Although, now that I think about it, is there ever a scenario where your timestamp would _not_ be newer if using `deployOnSave`?

**Comment by mkloubert** [comment]
@iFarmGolems @ryanpcmcquen 

Currently the feature works the following way:

* it checks for an existing version of the file on the remote system and compares two timestamps
* if the remote has a younger timestamp, it also will be check for differences in the data
* if that data is finally different, the remote file will be marked as newer

There is also a problem: The remote system may save and handle timestamps with more information, like `2017-01-02 03:04:05.678`, but for your local operating system (especially for [Node.js](https://nodejs.org/en/) runtime) it might be enough to save the same value as `2017-01-02 03:04:05` ... or the extension has no control to sync both timestamp, what may produce differences between two values.

This is why the extension has also check for data changes.

**Comment by iFarmGolems** [comment]
@ryanpcmcquen 

> Maybe a separate option where it compares the remote timestamp to the timestamp of the file before save would be useful for that scenario.

Yes, I was thinking exactly of this.

> Although, now that I think about it, is there ever a scenario where your timestamp would not be newer if using deployOnSave?

It would be, when you are not the only person working on the remote machine.

Imagine this scenario:

- I am working on some remote file (with my deployOnSave: true), so I upload on every change.
- Then someone else changes the same file on the server - timestamp on the server is now newer than my already existing file on my drive locally
- Then I come back to that file and press save - so it tries to upload the file. Now, it would be nice to compare my local file **from before I saved it**. (since that comparison can actually tell me if the file was actually changed)

I think that comparing the file before save would be a solution to this problem.

Anyway, great work @mkloubert, I really really love your extension!

**Comment by mikes-gh** [comment]
Hmm doesn't this break with sftp as the time stamps are set by the upload time not the modified time

**Comment by iFarmGolems** [comment]
@mikes-gh 

I don't know what the SFTP library used by this plugin is capable of, but if it could just query remote file for last modified timestamp, it would be possible to compare it to local file _before the actual upload_.

**Comment by ryanpcmcquen** [comment]
@iFarmGolems that is exactly the scenario I am in and what I was talking about when I said that there would never be a scenario where your timestamp would not be newer ... because it is comparing to your timestamp after save, rather than _before_ save.

From what @mikes-gh is saying that is now fixed? If that is the case, we can close this issue.
