### ISSUE TITLE
Preserve timestamps in sftp

### ISSUE THREAD

**Issue by mikes-gh** [mkloubert/vs-deploy#60]
Could sftp preserve the time stamps of the source files (-p option)

**Comment by mkloubert** [comment]
@mikes-gh 

Can you give me an example or link where such a `-p` option is used?

**Comment by mikes-gh** [comment]
sftp supports -p in get and put to preserve timestamp
I enclose an example done just now 2017-04-20 08:36
Note the file test.html has its original timestamp **Dec  8 11:20** after transfer.

This is important otherwise you lose sight of what has recently changed and you cant then run any sync tools that compare timestamps.
Without this the modified date of all files in the upload is the date of the upload.

I doesnt look like ssh2-sftp-client supports it

https://github.com/jyu213/ssh2-sftp-client/blob/master/src/index.js#L87

```
C:\Users\mikes>sftp dotnet@aesweb01
dotnet@aesweb01's password:
Connected to aesweb01.
sftp> ?
Available commands:
bye                                Quit sftp
cd path                            Change remote directory to 'path'
chgrp grp path                     Change group of file 'path' to 'grp'
chmod mode path                    Change permissions of file 'path' to 'mode'
chown own path                     Change owner of file 'path' to 'own'
df [-hi] [path]                    Display statistics for current directory or
                                   filesystem containing 'path'
exit                               Quit sftp
get [-afPpRr] remote [local]       Download file
reget [-fPpRr] remote [local]      Resume download file
reput [-fPpRr] [local] remote      Resume upload file
help                               Display this help text
lcd path                           Change local directory to 'path'
lls [ls-options [path]]            Display local directory listing
lmkdir path                        Create local directory
ln [-s] oldpath newpath            Link remote file (-s for symlink)
lpwd                               Print local working directory
ls [-1afhlnrSt] [path]             Display remote directory listing
lumask umask                       Set local umask to 'umask'
mkdir path                         Create remote directory
progress                           Toggle display of progress meter
put [-afPpRr] local [remote]       Upload file
pwd                                Display remote working directory
quit                               Quit sftp
rename oldpath newpath             Rename remote file
rm path                            Delete remote file
rmdir path                         Remove remote directory
symlink oldpath newpath            Symlink remote file
version                            Show SFTP version
!command                           Execute 'command' in local shell
!                                  Escape to local shell
?                                  Synonym for help
sftp> put -p test.html test.html
Uploading test.html to /home/dotnet/test.html
test.html                                     100%   16KB 805.9KB/s   00:00
sftp> ls -la
drwxrwx---    5 dotnet   dotnet       4096 Apr 20 08:32 .
drwxr-xr-x    4 root     root           32 Nov  5 15:38 ..
drwxr-xr-x    3 dotnet   dotnet         32 Feb  7 16:21 .aspnet
-rwxrwx---    1 dotnet   dotnet         18 Nov 20  2015 .bash_logout
-rwxrwx---    1 dotnet   dotnet        193 Nov 20  2015 .bash_profile
-rwxrwx---    1 dotnet   dotnet        231 Nov 20  2015 .bashrc
drwxr-----    3 dotnet   dotnet         18 Feb  7 16:35 .pki
-rw-r--r--    1 root     root     32407659 Mar 23 16:44 dotnet.1.1.1.tar,gz
-rwxrwx---    1 deploy   dotnet   53962133 Nov 18 16:49 dotnet.tar.gz
drwxrwx---    6 dotnet   dotnet       8192 Mar 24 09:31 reports
-rw-r--r--    1 dotnet   dotnet      16497 Dec  8 11:20 test.html
sftp>
```

**Comment by mkloubert** [comment]
Unfortunately thats right.

BUT: There is a way to do this the other direction: I am able to read the file information like the modfication timestamp from remote and can sync the timestamp of the local one with it, s. [utimes()](https://nodejs.org/api/fs.html#fs_fs_utimes_path_atime_mtime_callback).

**Comment by mikes-gh** [comment]
The other direction is no use to me as I only deploy from vscode to remote sftp.

I would imagine that would be the same for most users.

I think this can be done with the ssh2 np, packagedirectly

**Comment by mkloubert** [comment]
@mikes-gh Thank you very much!

**I have released version 8.12.0 that can now [executes commands on server](https://github.com/mkloubert/vs-deploy/wiki/target_sftp#execute-commands-on-server):**

```json
{
    "deploy": {
        "targets": [
            {
                "type": "sftp",

                // ...

                "uploaded": [
                    "touch -t ${mtime_touch} ${remote_file}"
                ]
            }
        ]
    }
}
```

The full list of placeholders / variables is available below the example on the [wiki page](https://github.com/mkloubert/vs-deploy/wiki/target_sftp#execute-commands-on-server).

**Comment by mikes-gh** [comment]
This is great just tested it.
Thankyou.
The last part for sftp sync for me  is something like

`deployOnlyChangedFiles.`

Which would work on comparing the timestamps of the remote to the local and only uploading the changed files.

That will save considerable time/bandwidth for sites with lots of libraries that don't change much.
Apologies if this exists.  I did have a good look.

Then perhaps we could have a meta parameter sync: true
Which sets mtimes and only copies files if differenent.

Hope this doesn't sound too demanding.
I can program in typescript so can help if required.

**Comment by mikes-gh** [comment]
Closing as 8.12.0 solves this exact issue. Thank you.
Sync is another issue tracked in #59

**Comment by mkloubert** [comment]
@mikes-gh 

This would be great!

Feal free to fork the repo and start programming inside a separate branch :-), so we can pull and merge new things later.
