### ISSUE TITLE
Allow for SSH_AUTH_SOCK substitution in target -> agent setting

### ISSUE THREAD

**Issue by rmrnc** [mkloubert/vs-deploy#63]
Hi,
Connecting via `ssh-agent` (on macOS) requires `agent` to point to the actual `ssh-agent` socket, e.g., `/private/tmp/com.apple.launchd.FPC20P3zeU/Listeners`. In order to assign the proper socket name, it would help if the environment variable `SSH_AUTH_SOCK` would be resolved. 

Unless I've missed a point, defining a corresponding value didn't help either

```json
"values": [
            {
                "name": "SSH_AUTH_SOCK",
                "type": "env"
            }
        ],
 "targets": [
            {
                "type": "sftp",
                ...
                "agent": "${SSH_AUTH_SOCK}",
                ...
           }
]
```
Thank you.

**Comment by mkloubert** [comment]
@rmrnc 

Thanks for the hint!

**Should be possible since version 8.10.1 now.**

**Comment by rmrnc** [comment]
Blimey, that was fast!!!
Appears to be working now, thank you!

**Comment by wmertens** [comment]
@mkloubert I had to search the issues to figure out how to do this. Could you change the sftp wiki page so it includes an example? I would do it but it seems the wiki is read-only?

**Comment by mkloubert** [comment]
@wmertens

You can post it here and I will apply it to the wiki.
