### ISSUE TITLE
make variables available for privateKey parameter

### ISSUE THREAD

**Issue by zelgerj** [mkloubert/vs-deploy#64]
Hi,

i'd love to have $homeDir in the privateKey parameter of a sftp target too make it abstract usable for all developers.

Cheers,
Johann

**Comment by mkloubert** [comment]
@zelgerj

Of course!

I will implement the feature this evening.

I think in about 8 hours, the feature will be available :-)

**Comment by zelgerj** [comment]
awesome! :-) thank you. Great plugin by the way! 👍

**Comment by mkloubert** [comment]
@zelgerj 

Thank you! :-)

**Should now be able since version 8.13.0.**

**Comment by zelgerj** [comment]
@mkloubert 

thanks, i just have updated to 8.13.0 but i can't get it work.
This is my definition:

```yml
"privateKey": "${homeDir}/.ssh/id_rsa"
```

is it correct?

**Comment by mkloubert** [comment]
@zelgerj 

Oops, I think there is a small bug.

Can you update to version 8.13.1 and try it again?

**Comment by zelgerj** [comment]
@mkloubert 

👍 looks good! thanks!
