### ISSUE TITLE
Deploy A Directory As The Base Directory

### ISSUE THREAD

**Issue by telekovar** [mkloubert/vs-deploy#66]
I am looking to deploy a build directory, via FTP, without transferring the build directory itself... just the contents. Is this possible?

**Comment by mkloubert** [comment]
@telekovar 

Can you give me an example?

**Comment by telekovar** [comment]
You have a "Source" directory, and a "Dist" directory. I'm uploading via FTP to a directory "website.com". I am seeking to upload the contents of "Dist" into that remote directory, instead of creating a new "website.com/dist" to upload into.

**Comment by mkloubert** [comment]
@telekovar 

I seems you only need a folder mapping for the `/dist` folder:

```json
{
    "deploy": {
        "targets": [
            {
                "type": "ftp",

                "mappings": [
                    {
                        "source": "/dist",
                        "target": "/"
                    }
                ],

                // ...
            }
        ]
    }
}
```

**Comment by telekovar** [comment]
@mkloubert 
That is exactly what I'm looking for. Thank you so much for your assistance in this. 👍
