### ISSUE TITLE
Suppress Deploy Popup

### ISSUE THREAD

**Issue by apoktechnology** [mkloubert/vs-deploy#68]
I'm using "deployOnSave": true which deploys to an FTP server. Is there a way to suppress the popup that occurs after you save? I'm referring to the bar that pops up at the top of the screen which has a blue "Info" button on the left and a blue "Close" button on the right. I've tried a few things that don't seem to work. Please advise if this is possible.

**Comment by mkloubert** [comment]
@apoktechnology

You can set `showPopupOnSuccess` to `(false)` in your [settings](https://github.com/mkloubert/vs-deploy/wiki#settings--).

**Comment by apoktechnology** [comment]
Thanks that worked when I added it under the deploy section. It didn't work under the packages, targets or host section which I tried in the past.
