### ISSUE TITLE
vscode version 1.12.2  command 'extension.deploy.file' not found

### ISSUE THREAD

**Issue by anshao** [mkloubert/vs-deploy#71]
macOS Sierra 10.12.3
vscode version 1.12.2 
vs-deploy version 9.1.1

![image](https://cloud.githubusercontent.com/assets/1137539/26137874/c2125f9c-3af7-11e7-98ec-9725abfb4933.png)

**Comment by anshao** [comment]
I have reinstalled the extension. But the problem still exist.

**Comment by mkloubert** [comment]
Is there something in your debug console (CTRL + SHIFT + Y) that may give some information?

Can you also try to submit (parts of) your config, so I can see what features you use and how you use them?

**Comment by anshao** [comment]
i really install the extension, and add a setting file in  workspace like '.vscode/.settings.json'

```
{
    "deploy": {
        "targets": [
            {
                "type": "sftp",
                "name": "hello world",
                "description": "my desc",
                "dir": "/",
                "host": "my ip", 
                "port": 22,
                "user": "hello", 
                "password": "password",
                "privateKey":"my key path",
                "mappings": [
                    {
                        "source": "src/",
                        "target": "www/my dir"
                    }
                ]
            }
        ]
    }
}
```

and i can't find any information about the extension from the debug console, said!

**Comment by anshao** [comment]
i reinstalled vscode version 1.12.2 and fixed the problem,thx.
