### ISSUE TITLE
[BUG] The file become empty when click the right menu of 'pull current file'

### ISSUE THREAD

**Issue by fanshengshuai** [mkloubert/vs-deploy#75]
this happened ONLY in the open document.

1. open a document.
2. click the right menu on the opened document.
3. click the pull current file menu item

**Comment by fanshengshuai** [comment]
it happened every 'pull current file' menu, but not always,  just sometimes, i'm not sure when or how

**Comment by hushedmo** [comment]
@fanshengshuai if you use FTP for deploy, try to use `jsftp `engine, check #65.
