### ISSUE TITLE
Using sftp upload file is very slow

### ISSUE THREAD

**Issue by yolo2013** [mkloubert/vs-deploy#76]
macOS
Webstorm or coda 2 need about 2-4s, but vs-deploy take 10-15s.
Please focus on this.

**Comment by mkloubert** [comment]
@yolo2013 

Can you post an example configuration you are currently using?

**Comment by yolo2013** [comment]
@mkloubert 

{
  "deploy": {
    "packages": [{
      "name": "xxx",
      "description": "Master",
      "targets": ["wxtest"],
      "files": [
        "some_dir/**"
      ],
      "deployOnSave": false
    }],
    "targets": [{
      "type": "sftp",
      "name": "wxtest",
      "description": "xxx",
      "dir": "/usr/local/tomcat7/webapps",
      "host": "192.168.1.xx",
      "port": 22,
      "user": "root",
      "password": "xxxxxx",
      "checkBeforeDeploy": true
    }]
  }
}

**Comment by mkloubert** [comment]
@yolo2013 

Have you tried to set the `checkBeforeDeploy` to `(false)`?

**Comment by mkloubert** [comment]
@yolo2013 

**I have released a new version 9.7.0.**

This speeds up deployments with `checkBeforeDeploy` = `(true)`.

If you want to increase the upload speed, you should set this setting to `(false)` (or remove it), if you do not need it.

**Comment by yolo2013** [comment]
@mkloubert I will try later. Thanks for your contributions.
