### ISSUE TITLE
How to start a specific browser after deployment?

### ISSUE THREAD

**Issue by mesterm** [mkloubert/vs-deploy#78]
After FTP deployment, I would like to start my Chrome browser with runtimeArg --disable-web-security for the site url/target.
How is this done in setings.json?

Any help is appreciated :)
/regards Michael

**Comment by mkloubert** [comment]
@mesterm 

You can use a [target operation](https://github.com/mkloubert/vs-deploy/wiki/targetoperations#open-) for this:

```json
{
    "deploy": {
        "targets": [
            {
                "type": "ftp",
                "name": "My FTP server",

                "deployed": [
                    {
                        "type": "open",

                        "target": "/path/to/chrome",
                        "arguments": [ "mysite.example.com", "--disable-web-security" ]
                    }
                ]
            }
        ]
    }
}
```

This will open `/path/to/chrome` with the arguments `mysite.example.com` and `--disable-web-security` after a successful deployment.

If the chrome folder is defined in your `PATH`, you can simply use `chrome` as value for the `target` property.

In the target property you are also able to use [placeholders](https://github.com/mkloubert/vs-deploy/wiki/values).

**Comment by mesterm** [comment]
Great. Thank you for your prompt reply.
Perfect for a newcomer to understand how settings.json works. :)

**Comment by mesterm** [comment]
Great. Thank you for your prompt reply.
Perfect for a newcomer to understand how settings.json works. :)

*Argument --disable-web-security is accepted BUT have no effect :(*

Med herlig hilsen
Michael

2017-05-26 16:45 GMT+02:00 Marcel Kloubert <notifications@github.com>:

**Comment by mkloubert** [comment]
@mesterm 

Is there a way how can you make it work, like executing Chrome from the command line, e.g.?

**Comment by mesterm** [comment]
Yes using command prompt like this
**"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --user-data-dir="C:/Chrome dev session" --disable-web-security www.dr.dk**

or in my launch.json for debugging Chrome
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome, no web security",
            "url": "http://www.dr.dk",
            "webRoot": "${workspaceRoot}",
            "runtimeArgs": [
              "--disable-web-security",
              "--user-data-dir",
              "--remote-debugging-port=9222"
            ]

/regards Michael

**Comment by mkloubert** [comment]
@mesterm

This should represent your working command line options:

```json
{
    "deploy": {
        "targets": [
            {
                // ...

                "deployed": [
                    {
                        "type": "open",

                        "target": "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
                        "arguments": [ "--user-data-dir=\"C:/Chrome dev session\"",
                                       "--disable-web-security",
                                       "www.dr.dk" ]
                    }
                ]
            }
        ]
    }
}
```

**Comment by mesterm** [comment]
Also my approach.
But --disable-web-security has no effect

**Comment by mkloubert** [comment]
@mesterm 

Does that mean you get NO warning message at the top of the browser area in Chrome, that tells you are trying to use `--disable-web-security`?

![2017-05-26 21_24_29-dr forsiden - tv radio nyheder og meget mere fra dr dk](https://cloud.githubusercontent.com/assets/4951215/26509626/d7a30abe-4259-11e7-8772-e6802a787cff.png)

**Or if you get this kind of message:** Is the flag still supported, s. [Does --disable-web-security work in Chrome anymore?](https://stackoverflow.com/questions/17679399/does-disable-web-security-work-in-chrome-anymore)

I tested this with the following Chrome version:

![2017-05-26 21_30_13-uber](https://cloud.githubusercontent.com/assets/4951215/26509767/8b97ced8-425a-11e7-9639-f3fedb2f4bd8.png)

**Comment by mesterm** [comment]
I am using the same Chrome version
Using command line I get the warning mesage, but not from within settings.json 

This launch.json for Chrome debugging works fine giving a warning message
```
{
    "version": "0.2.0",
    "configurations": [
        
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://mbswebapp/index.html",
            "webRoot": "${workspaceRoot}",
            "runtimeArgs": [
              "--disable-web-security",
              "--user-data-dir",
              "--remote-debugging-port=9222"
            ]
        },
        {
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "webRoot": "${workspaceRoot}"
        }
    ]
}

```
Strange. . .

OR the case is how a windows process is created.
Writing this in a command window works every time
**"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --user-data-dir="C:/Chrome dev session" --disable-web-security mesterm.dk/MBS**

BUT setttings.json
```
"deployed": [
                    {
                        "type": "open",

                        "target": "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
                        "arguments": [ "--user-data-dir=\"C:/Chrome dev session\"", "--disable-web-security", "mesterm.dk/MBS" ]
                    }
                ]
```
now prompt me with this error
![image](https://cloud.githubusercontent.com/assets/5729757/26513306/1b2bbdba-426b-11e7-8ece-485a6fddae1a.png)

Is there a way to fire a full command line in a command window (cmd.exe) from whitin settings.json ?

**Comment by mkloubert** [comment]
@mesterm 

Yes, you can write this into a batch file, that you can put into the root directory of your workspace, e.g.

**open_chrome_after_deploy.cmd**

```batch
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --user-data-dir="C:/Chrome dev session" --disable-web-security mesterm.dk/MBS
```

In your settings, you should write this:

```json
{
    "deploy": {
        "targets": [
            {
                // ...

                "deployed": [
                    {
                        "type": "open",

                        "target": "open_chrome_after_deploy.cmd",
                        "runInTerminal": true
                    }
                ]
            }
        ]
    }
}
```

When I test this, I do not get the popup anymore.

The `runInTerminal` will run the batch in an integrated Terminal of VSCode instead of opening a new command line window.

Is thats the right way?

**Comment by mesterm** [comment]
YES !!, thank you very much. Greatly appreciate your help :)
This is the solution for now.

**open_chrome.cmd** (in workspace root)
`"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --user-data-dir="C:/Chrome dev session" %*`

In **settings.json** deploy/targets
```
"deployed": [
                    {
                        "type": "open",

                        "target": "open_chrome.cmd",
                        "arguments": [ "--disable-web-security", "mesterm.dk/MBS" ],
                        "runInTerminal": true
                    }
                ]

```

An idea could be something like this to avoid the cmd file :)
```
               "deployed": [
                    {
                        "type": "open",

                        "command": "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
                        "arguments": [ "--user-data-dir=\"C:/Chrome dev session\"", "--disable-web-security", "mesterm.dk/MBS" ],
                        "runInTerminal": true
                    }
                ]
```

Best regards
Michael
