### ISSUE TITLE
beforeDeploy script task

### ISSUE THREAD

**Issue by mikemaggire** [mkloubert/vs-deploy#86]
I would like to run a js task before to deploy : 
```
npm run build:test
```
with `build:test` defined as a task in my `setting.json`.
Both my js script and my `setting.json` are stored in my vscode workspace directory.

I encounter the following issues :  
a) **The task runs asynchronously.** I'm a newbi in js, may I use `var exec = require('child_process').execSync;` rather than `var exec = require('child_process').exec;` to avoid that the deployement start before my javascript beforeDeploy task end ? Thank in advance for any help.

b) **The task executes at the root of my vscode install path** and so it doesn't find my `setting.json` in the path. Do I make something wrong ? (here under my `package.json`).

c) So I try to use **${workspaceRoot} value but the string seems not evaluated**. I've red [here](https://github.com/mkloubert/vs-deploy/wiki/values) that this value should be automatically provided by the extension. What is missing ?

Thank you for any help

```
    "deploy": {
        "packages": [
            {
                "name": "my website",
                "description": "Package of my website",
                "files": [
                    "_site_ready2deploy/**"
                ],
           }
        ],

        "targets": [
            {
                "type": "local",
                "name": "acceptance",
                "dir": "\\\\BIGMAMA\\web\\web_acceptance\\myvsproject",
                "mappings": [
                    {
                        "source": "_site_ready2deploy",
                        "target": "/"
                    }],
                "empty": true,
                "beforeDeploy": [ 
                    {
                        "type": "script",
                        "script": "build_test.js",
                        "options": {
                            "path": "${workspaceRoot}",
                            "task": "build:test"
                        }
                    }]
       }]
```

**Comment by mkloubert** [comment]
@mikemaggire

Options of a [script](https://github.com/mkloubert/vs-deploy/wiki/targetoperations#script--1) are not parsed, because the extension cannot decide if you really want to parse the data (in it) or not.

But you can use [replaceWithValues()](https://mkloubert.github.io/vs-deploy/interfaces/_contracts_.deployscriptoperationarguments.html#replacewithvalues) of `args` (s. below).

```javascript
var child_process = require('child_process');

exports.execute = function( args ) {
    // the object from 'beforeDeploy' of
    // your settings
    var options = args.options;

    // will be replace all placeholders, defined in your settings
    // and the predefined ones
    var path = args.replaceWithValues(options.path);

    // "build:test"
    var task = options.task;

    return new Promise(function(resolve, reject) {
        // create a child process
        // by executing "npm build:task"
        var cp = c.execFile('npm', [ task ], {
            cwd: path,  // working directory for 'npm'
        }, function(err) {
            if (err) {
                reject(err);    // could not start process
            }
        });

        cp.once('close', function(exitCode) {
            if (0 == exitCode) {
                resolve();  // test OK
            }
            else {
                // your build test should return an
                // exit code <> 0
                reject(new Error('Test failed with exit code: ' + exitCode));
            }
        });
    });
};
```

**Comment by mikemaggire** [comment]
Thank you @mkloubert
