### ISSUE TITLE
Feature Request: Deploy Open Files in Workspace

### ISSUE THREAD

**Issue by telekovar** [mkloubert/vs-deploy#89]
I'm looking for a way to deploy all the files I currently have open. If I'm working on a project and touch multiple files, I would like to easily deploy all of them without having to use the document tree to push one at a time.

**Comment by mkloubert** [comment]
@telekovar 

I currently work on a new [major release](https://github.com/mkloubert/vs-deploy/tree/v10) and will add this feature there.

I hope that I can release the new version with all new features this week.

**Comment by quannda** [comment]
Hi @mkloubert 
i would also looking for an option to deploy all changed files are waiting for commit in git.

**Comment by mkloubert** [comment]
@telekovar @quannda 

Sorry for the very late answer!

I am currently working on a completely refactored and clean version of that extension, called [vscode-deploy-reloaded](https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-deploy-reloaded).

This has currently both of your requested features:

* deploy **all open files**

![Demo Deploy or pull all opened files](https://raw.githubusercontent.com/mkloubert/vscode-deploy-reloaded/master/img/demo13.gif)

* deploy **a git commit**

![Demo Deploy git commit](https://raw.githubusercontent.com/mkloubert/vscode-deploy-reloaded/master/img/demo12.gif)
