### ISSUE TITLE
Look for parent folder's settings if the current workspace does not have vs-deploy configured

### ISSUE THREAD

**Issue by carlosesilva** [mkloubert/vs-deploy#90]
Could you please make so that if the current workspace root directory does not have the deploy settings configured then it will look for its ancestor's settings? Sublime SFTP does this and it was a great feature that I miss in vscode.

Let's say that I have the following file structure:

- wordpress
    - .vscode
        - settings.json
    - wp-content
        - plugins
            - pluginA
                - file.php
            - pluginB
            - pluginC
            - ...
            - pluginZ

The `wordpress` folder has the `.vscode` folder with the `settings.json` file which is configured to deploy files on save.

If I were to open the `pluginA` folder directly on a new instance of vscode and make changes to `file.php`, I would like for it to find the `wordpress` folder's vs-deploy settings and still deploy the files on save.

It would be a lot better than having to duplicate the `settings.json` file for each plugin folder (which will all just deploy to the same server with the same settings)

**Comment by mkloubert** [comment]
@carlosesilva 

I currently work on a new [major release](https://github.com/mkloubert/vs-deploy/tree/v10) and will add this feature there.

I hope that I can release the new version with all new features this week.

**Comment by carlosesilva** [comment]
Hi @mkloubert,

Thank you so much for your amazing plugin and for releasing v10!!
Did this feature get included in it and if so, do I have to do anything to activate the feature?

Thanks!!

**Comment by mkloubert** [comment]
@carlosesilva 

The feature is now available in the [new extension](https://github.com/mkloubert/vscode-deploy-reloaded).

Thanks for the star, btw! :-D

**Comment by carlosesilva** [comment]
Thank _YOU_ for all your efforts! Your work is awesome and it certainly deserves a star! =]
I did just test it out and it worked perfectly! Thanks so much!!
