### ISSUE TITLE
target tamplate

### ISSUE THREAD

**Issue by minomikula** [mkloubert/vs-deploy#91]
Hello,

I have multiple sftp targets with small differences. Is it possible to have one template target to share the common part? I tried to use "map" target, but I lost compare files feature.

Thanks!

**Comment by mkloubert** [comment]
@minomikula 

You can define `inheritFrom` property in a target. This can contain one or more target names from where to import settings from. In that case, it should be the name of your 'template' target.

You also can set `isHidden` to `(true)` in your 'template' target, so you can hide it in the GUI.

```json
{
    "deploy": {
        "targets": [
            {
                "name": "My FTP template",
                "type": "ftp",

                "user": "my-ftp-user",
                "password": "my-ftp-pwd",

                "isHidden": true
            },

            {
                "name": "FTP server #1",

                "inheritFrom": [ "My FTP template" ],

                "host": "ftp1.example.com",

                "isHidden": false
            },
            {
                "name": "FTP server #2",

                "inheritFrom": [ "My FTP template" ],

                "host": "ftp2.example.com",

                "isHidden": false
            },
        ]
    }
}
```

As use can see, anything is taken from `My FTP template` and overwritten with the data of `FTP server #1` and `FTP server #2`.

**Comment by minomikula** [comment]
Thank you very much! Works like a charm.
