### ISSUE TITLE
There is an undocumented option that can be applied to FTP

### ISSUE THREAD

**Issue by carlwhittick** [mkloubert/vs-deploy#92]
The option "rejectUnauthorized" for connections using the node-ftp plugin is not mentioned in the documentation. 

This option would normally be inside a "secureOptions" object (which doesn't work). I was looking into that bit of code to try and implement a workaround and found exactly the functionality I needed built in! 

If you let me know the best place to mention this in the docs I would be to make the changes required :)

**Comment by mkloubert** [comment]
@carlwhittick 

Sorry that I answer so late!

Feel free to fork the repository, make the required changes there and send it back as pull request.

Btw.: Can you post this "workaround" here or some code that demonstrates the issue?
