### ISSUE TITLE
[Feature Request] Support of Ed25519 SSH keys

### ISSUE THREAD

**Issue by rmrnc** [mkloubert/vs-deploy#99]
Hi,
Unless I am missing something, Ed25519 SSH keys are not supported for sftp targets. Not the end of the world, but a bit annoying.

Thank you.

**Comment by mkloubert** [comment]
@rmrnc 

I am using [ssh2-sftp-client](https://www.npmjs.com/package/ssh2-sftp-client) for SFTP.

I am not sure if it is possible to use the key format there.

Is there a way to convert?

**Comment by mkloubert** [comment]
@rmrnc 

I have find a way to convert keys. I am using [sshpk](https://www.npmjs.com/package/sshpk) module for that.

**Since version 9.32.0, you can set the `privateKeySourceFormat` property to define the [source format](https://github.com/joyent/node-sshpk#parseprivatekeydata-format--auto-options) of your private key.**

```json
{
    "deploy": {
        "targets": [
            {
                "type": "sftp",

                "user": "mkloubert",

                "privateKey": "/.ssh/id_rsa",
                "privateKeySourceFormat": "auto",

                // ....
            }
        ]
    }
}
```

By default it will convert this to `ssh` format, This change be changed by setting up `privateKeyTargetFormat`.

**Comment by rmrnc** [comment]
Thank you for your quick response, but I am not entirely sure whether we are on the same page. I'd opted intentionally for elliptic-curve keys and specifically for an Ed25519 key (admittedly, a quite popular choice within the security community). Therefore, I am afraid to say that "(format) conversion" is not the issue. It appears to me, that the SSH client you are employing has omitted support for this kind of SSH keys. Let me know whether you need more information about the cryptographic background.

**Comment by mkloubert** [comment]
@rmrnc 

Ah, OK. I wasn't really sure if a conversion is the really answer.

But on the other hand I have implemented a new, useful feature :D

Yes, tell me the background. What I currently see is, that this is a problem of the SSH client.

But I am not sure if there is a NodeJS module that supports this feature.

**Comment by HLFH** [comment]
Related to: https://github.com/joyent/node-sshpk/issues/72
